---
abstract: 'A Perl module for using Google Spreadsheets API.'
author:
  - 'Nobuo Danjou <nobuo.danjou@gmail.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-Spreadsheets
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Crypt::SSLeay: 0
  LWP::UserAgent: 0
  Moose: 0.34
  Net::Google::AuthSub: 0
  Path::Class: 0
  URI: 0
  XML::Atom: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
